### ISSUE TITLE
Allow multiple swagger definitions on one endpoint

### ISSUE THREAD

**Issue by sarnowski** [zalando-stups/twintip-crawler#5]
The current schema-discovery endpoint (".well-known/schema-discovery") is expected to give the following result:

``` json
{
    "schema_url": "/swagger.json",
    "schema_type": "swagger-2.0",
    "ui_url": "/ui/"
}
```

In order to allow multiple definitions and to be able to distinguish them, introduce the notion of "named" definitions:

``` json
{
    "named": {
        "mydef1": {
            "schema_url": "/swagger1.json",
            "schema_type": "swagger-2.0",
            "ui_url": "/ui1/"
        },
        "mydef2": {
            "schema_url": "/swagger2.json",
            "schema_type": "swagger-2.0",
            "ui_url": "/ui2/"
        },
    }
}
```

Use the "named" key in order to provide backwards compatibility. As a rule, either a top level definition description is given XOR the "named" key with named definitions under it.

**Comment by whiskeysierra** [comment]
Why not just an array with schemas?

```json
{
  "schemas": [
    {
      "schema_url": "/swagger1.json",
      "schema_type": "swagger-2.0"
    },
    {
      "schema_url": "/swagger2.json",
      "schema_type": "swagger-2.0"
    }
  ]
}
```

**Comment by hjacobs** [comment]
@whiskeysierra :+1: I would also remove the "schema_" prefix and rename URL to "path" (as it's only the path component).

```
{
  "schemas": [
    {
      "path": "/swagger1.json",
      "type": "swagger-2.0"
    },
    {
      "path": "/swagger2.json",
      "type": "swagger-2.0"
    }
  ]
}
```

**Comment by sarnowski** [comment]
Why I want names is, that we then can better get a grip on the different schemas. Especially for displaying the APIs in YourTurn. Currently it just gives you a link to the API, if we support multiple schemas, we have to provide multiple links and they should haev proper names to be able to distinguish them fastly.

**Comment by ePaul** [comment]
When more than one version of API definition format is supported (or even before), it might also be useful to allow mentioning multiple formats of the same API. They then would have the same name (and whoever is using the crawled data can then decide which of the formats to use).

For that a format like this might be sensible:

```json
{
  "schemas": [
    {
      "name": "Petshop API",
      "path": "/swagger1.json",
      "type": "swagger-2.0"
    },
    {
      "name": "Petshop API",
      "path": "/swagger1-3.json",
      "type": "openapi-3.0"
    },
    {
      "name": "Car shop API",
      "path": "/swagger2.json",
      "type": "swagger-2.0"
    }
  ]
}
```

**Comment by fmueller** [comment]
Providing many api definitions per service would violate separation of concerns. So, I would not like to add feature support for this in Twintip.

**Comment by whiskeysierra** [comment]
> Providing many api definitions per service would violate separation of concerns.

For new services this is very reasonable, but unfortunately we do have a whole lot of legacy services that violate this. Most of those we will strip apart but this was meant to deal with that issue during migration.

**Comment by fmueller** [comment]
@whiskeysierra Are willing to add api discovery endpoints to these legacy services?

**Comment by whiskeysierra** [comment]
We at least had the idea back then.... :yum:

**Comment by bocytko** [comment]
> > Providing many api definitions per service would violate separation of concerns.
> For new services this is very reasonable, but unfortunately we do have a whole lot of legacy services that violate this. Most of those we will strip apart but this was meant to deal with that issue during migration.

Plus, we have services having REST APIs and event APIs. We don't want to have a `/.well-known/data-discovery`, right? ;-)

**Comment by tfrauenstein** [comment]
1) Events are handled differently than REST APIs. 
But yes, we will build a Event Scheme Discovery service on top of Nakadi. 
And Nakadi should also support reporting functions about which applications produce or consume events -- I will put this in the Nakadi backlog. 

2) I do not agree with the general statement: Providing >1 api definitions per service application violates separation of concerns and should not be supported. 
Possible legacy constraints have been mentioned. Other arguments, for example:  
a) Separation of concern also has its trade-offs and no absolute primacy. b) It often makes sense to separate service resource api from service config and operation api

**Comment by fmueller** [comment]
This repository is migrated to a mono repository, issue is now at https://github.com/zalando-incubator/api-discovery/issues/3
