### ISSUE TITLE
Do not log WARNings for undiscoverable services

### ISSUE THREAD

**Issue by hjacobs** [zalando-stups/twintip-crawler#6]
As it's "normal" behavior to have applications without Swagger API specs, TWINTIP should not warn about every undiscoverable service. The current behavior is just spamming the logs. I would propose changing the log level to INFO (IMHO we should get of "WARN" as a log level altogether).

**Comment by sarnowski** [comment]
+1 user "errors" shouldn't be logged - we don't care and communicate via the status message to the user, not our logging.

**Comment by hjacobs** [comment]
@sarnowski BTW the same applies for Friboo and Swagger1st, see https://github.com/zalando-stups/friboo/issues/34

**Comment by sarnowski** [comment]
done
