### ISSUE TITLE
Support YAML format

### ISSUE THREAD

**Issue by alexkops** [zalando-stups/twintip-crawler#8]
The Zalando API guild specifies that the swagger definition can be delivered in JSON or YAML, and the latter is preferred.
So I think twintip should accept both formats, or else you'd have to either maintain your definition in two formats or convert them on the fly (extra effort).

**Comment by okthatsneat** [comment]
+1

**Comment by hjacobs** [comment]
:+1:

**Comment by fmueller** [comment]
+1

**Comment by hjacobs** [comment]
@fmueller I get from your +1 that you will work on this :smirk: ?

**Comment by fmueller** [comment]
Seems so, if someone with more clojure experience is reviewing my coding attempt. ;-)
